name: cask CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cask:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Audit cask
        run: brew audit --cask --strict --online ./Casks/ascension.rb

      - name: Prepare app directory
        run: mkdir -p "$RUNNER_TEMP/Applications"

      - name: Install cask
        run: brew install --cask --no-quarantine --appdir="$RUNNER_TEMP/Applications" ./Casks/ascension.rb

      - name: Uninstall cask
        run: brew uninstall --cask ascension
